# ENCODER_ENABLE = no
# OLED_DRIVER_ENABLE = no
# EXTRAKEY_ENABLE  = no

# CONSOLE_ENABLE = yes
# NO_USB_STARTUP_CHECK = yes

VIA_ENABLE = yes
BOOTMAGIC_ENABLE = lite
LEADER_ENABLE = no
FAUXCLICKY_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
KEY_LOCK_ENABLE = no
TERMINAL_ENABLE = no
MOUSEKEY_ENABLE = no
